# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
container_image = file:///projects/bacteriology_tran_data/apptainer/hmmer.sif

executable = 01-hmmer.sh
arguments = $(sample) $(hmm) $(staging)

staging = /staging/ptran5/

transfer_input_files = file://$(staging)/$(sample)_scaffolds_proteins.faa,file://$(staging)/HiteLab/HMM/$(hmm).HMM
transfer_output_files = $(sample)_vs_$(hmm).fasta
transfer_output_remaps = "$(sample)_vs_$(hmm).fasta=file://$(staging)/HiteLab/hmm_out/$(sample)_vs_$(hmm).fasta"

log = logs/hmm_$(sample)_$(hmm)_$(cluster)_$(process).log
error = logs/hmm_$(sample)_$(hmm)_$(cluster)_$(process).err
output = logs/hmm_$(sample)_$(hmm)_$(cluster)_$(process).out

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

request_cpus = 8
request_memory = 16GB
request_disk = 15GB      

queue sample,hmm from sample_hmm_combinations.csv
